exclude: >
  (?x)(
      ^setup.py|
      ^scratch/
  )$
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy -p fastapitableau
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest
        pass_filenames: false
        always_run: true
