name: ci

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10-dev]

    steps:
    - uses: actions/checkout@v2

    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock

    - name: Lint
      run: just lint

    - name: Test
      run: just test

    - name: Generate coverage report
      if: matrix.python-version == 3.9
      run: |
        pipenv run pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.9
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests

    - name: Publish MkDocs
      if: github.ref == 'refs/heads/main' && matrix.python-version == 3.9
      run: pipenv run mkdocs gh-deploy
